### ISSUE TITLE
backup test failure due to inconsistent automatic container names

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/portal-compose#117] opened 2022-03-02 12:07 UTC
**Bug description**
`bash run_tests.sh` fails for the backup test, on archlinux (linux 5.16) using docker-compose 2.2.3:

```
Test the backup functions                                                                                                                                                 
----------------------------------------                                                                                                                                  
Error: No such container: portal-compose_backup_1
```

The container is named `portal-compose-backup-1` on my machine.

**Expected behavior**

all tests should pass.

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [ ] MaRDI_Project has been assigned as project

**Comment by dajuno** [comment] 2022-03-02 13:29
Solution: assign a fixed name for the backup container: "mardi-backup" and modify the test script (71ab6b0), also adapt  the CI test to use the new container name (c8601e3)

**Comment by Hyper-Node** [comment] 2022-03-02 14:22
Workflow with creating feature branch and linking the issue is ok. If all mentioned commits are in PR they don't have to be specificly mentioned. The created issues are assigned to the project MaRDI T5 Overview, this is a central view for all issues over all repository.

**Closed** 2022-03-03 08:31 UTC
Labels: bug
