### ISSUE TITLE
Set up metrics

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#15] opened 2021-12-22 08:13 UTC
Follow

https://medium.com/platform-engineering/monitoring-traefik-with-grafana-1d037af5b952

However, there are several things that are not clear to me:
- [ ] do we need to enable insecure api access in traefik. (maybe not 
see also https://www.kuerbis.org/2021/01/native-traefik-metriken-mit-prometheus-sammeln/)
- [ ] can we get the passwords from the .env file

**Comment by aot29** [comment] 2022-03-14 14:10
duplicate of #16

**Closed by aot29** 2022-03-14 14:10 UTC
